'use strict';

/**
 * 求职星计划 — 目标公司注册表（阶段 2 框架核心）
 *
 * 每家公司标好：用哪套招聘系统（adapter）+ 抓取参数 + 状态。
 * adapter 取值：
 *   'zhiye'  —— 北森 zhiye.com，已实现
 *   null     —— 自研/其他招聘系统，待适配（pending）
 *
 * 抓取时按 company.name 查表 → 分发到对应适配器，前端不用关心底层系统细节。
 */

// 公司覆盖层 apply.overrides：候选链（登录方式/解析按钮/字段名/下拉）没覆盖的特例，验证阶段发现后回填。
// 字段约定（候选链默认覆盖的不填，只有特例才填）：
//   applyButtonText   投递按钮文本（候选链默认找「投递/申请/apply」）
//   parseButtonSelector 解析按钮额外选择器（候选链默认找 span/button/短文本）
//   fieldLabelAttr    字段名来源覆盖（候选链默认 data属性/label/placeholder）
//   dropdownSelector  下拉选项选择器覆盖（候选链默认 role=combobox/class含select）
const COMPANIES = [
  // ============ 互联网大厂（自研招聘系统，待适配） ============
  { group: '互联网', name: '腾讯', adapter: 'tx', url: 'https://join.qq.com', reach: { type: 'navigate', entryUrl: 'https://join.qq.com' } },
  { group: '互联网', name: '阿里巴巴', adapter: 'ali', url: 'https://campus-talent.alibaba.com/campus/position', reach: { type: 'direct', urlTemplate: 'https://campus-talent.alibaba.com/campus/position/{id}?deptCodes=' } },
  { group: '互联网', name: '字节跳动', adapter: 'byte', url: 'https://jobs.bytedance.com', reach: { type: 'direct', urlTemplate: 'https://jobs.bytedance.com/campus/position/{id}/detail' } },
  { group: '互联网', name: '美团', adapter: 'mt', url: 'https://zhaopin.meituan.com/web/campus', reach: { type: 'navigate', entryUrl: 'https://zhaopin.meituan.com/web/campus' } },
  { group: '互联网', name: '京东', adapter: 'jd', url: 'https://campus.jd.com', reach: { type: 'direct', urlTemplate: 'https://campus.jd.com/#/details?id={id}' } },
  { group: '互联网', name: '网易', adapter: 'ne', url: 'https://campus.163.com', reach: { type: 'direct', urlTemplate: 'https://campus.163.com/app/detail/index?id={id}&projectId=103' } },
  { group: '互联网', name: '百度', adapter: 'baidu', url: 'https://talent.baidu.com', reach: { type: 'direct', urlTemplate: 'https://talent.baidu.com/jobs/detail/GRADUATE/{id}' } },
  { group: '互联网', name: '拼多多', adapter: 'pdd', url: 'https://careers.pddglobalhr.com/campus/grad', reach: { type: 'direct', urlTemplate: 'https://careers.pddglobalhr.com/campus/grad/detail?positionId={id}' } },
  { group: '互联网', name: '快手', adapter: 'ks', url: 'https://campus.kuaishou.cn', reach: { type: 'navigate', entryUrl: 'https://campus.kuaishou.cn' } },
  { group: '互联网', name: '小红书', adapter: 'xhs', url: 'https://job.xiaohongshu.com', reach: { type: 'direct', urlTemplate: 'https://job.xiaohongshu.com/social/position/{id}' } },
  { group: '互联网', name: '哔哩哔哩', adapter: 'bili', url: 'https://jobs.bilibili.com', reach: { type: 'navigate', entryUrl: 'https://jobs.bilibili.com/campus/positions' } },
  { group: '互联网', name: '滴滴', adapter: 'moka', moka: { org: 'didiglobal', siteId: '96064', base: 'https://campus.didiglobal.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://campus.didiglobal.com' },
  { group: '互联网', name: '蚂蚁集团', adapter: 'ant', url: 'https://talent.antgroup.com' },
  { group: '消费电子', name: '小米', adapter: 'byte', byte: { base: 'https://xiaomi.jobs.f.mioffice.cn', campusPath: '/campus/' }, url: 'https://xiaomi.jobs.f.mioffice.cn', reach: { type: 'direct', urlTemplate: 'https://xiaomi.jobs.f.mioffice.cn/campus/position/{id}/detail' } },
  { group: '消费电子', name: '华为', adapter: 'huawei', url: 'https://career.huawei.com', reach: { type: 'direct', urlTemplate: 'https://career.huawei.com/reccampportal/portal5/campus-recruitment-detail.html?jobId={id}' } },
  { group: '消费电子', name: 'OPPO', adapter: 'oppo', url: 'https://careers.oppo.com', reach: { type: 'direct', urlTemplate: 'https://careers.oppo.com/#/campus/talent/positionDetail/{id}' } },
  { group: '消费电子', name: 'vivo', adapter: 'vivo', url: 'https://hr-campus.vivo.com', reach: { type: 'direct', urlTemplate: 'https://hr-campus.vivo.com/zpdetail/{id}' } },
  { group: '游戏', name: '米哈游', adapter: 'mhy', url: 'https://jobs.mihoyo.com', reach: { type: 'direct', urlTemplate: 'https://jobs.mihoyo.com/#/campus/position/{id}' } },
  { group: '消费电子', name: '大疆', adapter: 'moka', moka: { org: 'dji', siteId: '143359', base: 'https://apply.careers.dji.com', section: 'campus' }, url: 'https://careers.dji.com' },
  { group: '科技', name: '商汤', adapter: 'byte', byte: { base: 'https://hr-jobs.sensetime.com', campusPath: '/edu/' }, url: 'https://hr-jobs.sensetime.com', reach: { type: 'direct', urlTemplate: 'https://hr-jobs.sensetime.com/edu/position/{id}/detail' } },
  { group: '互联网', name: '贝壳', adapter: 'zhiye', base: 'https://campus.ke.com', url: 'https://campus.ke.com' },
  // zhiye/hotjob 系统（免费点亮）
  { group: '科技', name: '科大讯飞', adapter: 'zhiye', subdomain: 'iflytek', path: 'campus/jobs' },
  { group: '互联网', name: '360', adapter: 'zhiye', subdomain: '360campus', path: 'campus/jobs' },
  { group: '消费电子', name: '荣耀', adapter: 'hotjob', suiteId: 'SU60eea919bef57c1023f6fe78', base: 'https://career.honor.com', url: 'https://career.honor.com', reach: { type: 'direct', urlTemplate: 'https://career.honor.com/SU60eea919bef57c1023f6fe78/pb/posDetail.html?postId={id}&postType=campus' } },
  // Moka 系统（moka 适配器）
  { group: '互联网', name: '携程', adapter: 'ctrip', url: 'https://job.ctrip.com', reach: { type: 'direct', urlTemplate: 'https://job.ctrip.com/campus-recruitment/trip/37757#/campus/job-detail/{id}' } },
  { group: '互联网', name: '唯品会', adapter: 'moka', moka: { org: 'vipshophr', siteId: '10039', base: 'https://app-tc.mokahr.com', section: 'campus' }, url: 'https://app-tc.mokahr.com/campus-recruitment/vipshophr/10039' },
  { group: '互联网', name: '新浪微博', adapter: 'moka', moka: { org: 'sina', siteId: '43535', base: 'https://career.sina.com.cn', section: 'social' }, url: 'https://career.sina.com.cn/social-recruitment/sina/43535/' },
  { group: '互联网', name: '搜狐', adapter: 'moka', moka: { org: 'sohu', siteId: '43256', base: 'https://hr.sohu.com', section: 'social' }, url: 'https://hr.sohu.com/social-recruitment/sohu/43256' },
  { group: '互联网', name: '爱奇艺', adapter: 'zhiye', subdomain: 'iqiyi', path: 'campus/jobs' },
  { group: '互联网', name: '得物', adapter: 'byte', byte: { base: 'https://campus.dewu.com', campusPath: '/578078/position/' }, url: 'https://campus.dewu.com', reach: { type: 'direct', urlTemplate: 'https://campus.dewu.com/578078/position/{id}/detail' } },
  // Moka 家族扩展（参考 job-pro，org/siteId 已逆向）
  { group: '半导体', name: '寒武纪', adapter: 'moka', moka: { org: 'cambricon', siteId: '44201', base: 'https://app.mokahr.com', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/cambricon/44201' },
  { group: '科技', name: 'DeepSeek', adapter: 'moka', moka: { org: 'high-flyer', siteId: '140576', base: 'https://app.mokahr.com', section: 'social' }, url: 'https://app.mokahr.com/social-recruitment/high-flyer/140576' },
  { group: '科技', name: '银河通用', adapter: 'moka', moka: { org: 'yinhetongyong', siteId: '165929', base: 'https://app.mokahr.com', section: 'social' }, url: 'https://app.mokahr.com/social-recruitment/yinhetongyong/165929' },
  { group: '汽车', name: '吉利', adapter: 'moka', moka: { org: 'geely', siteId: '96123', base: 'https://app.mokahr.com', section: 'social' }, url: 'https://app.mokahr.com/social-recruitment/geely/96123' },
  { group: '科技', name: '旷视', adapter: 'moka', moka: { org: 'megviihr', siteId: '38642', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/megviihr/38642' },
  { group: '科技', name: '阶跃星辰', adapter: 'moka', moka: { org: 'step', siteId: '94904', base: 'https://app.mokahr.com', section: 'social' }, url: 'https://app.mokahr.com/social-recruitment/step/94904' },
  // 飞书 ATSX 家族扩展（host + campusPath 已逆向）
  { group: '科技', name: '百川智能', adapter: 'byte', byte: { base: 'https://cq6qe6bvfr6.jobs.feishu.cn', socialPath: '/baichuanzhaopin/position/', section: 'social' }, url: 'https://cq6qe6bvfr6.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://cq6qe6bvfr6.jobs.feishu.cn/baichuanzhaopin/position/{id}/detail' } },
  { group: '科技', name: 'MiniMax', adapter: 'byte', byte: { base: 'https://vrfi1sk8a0.jobs.feishu.cn', campusPath: '/379481/position/' }, url: 'https://vrfi1sk8a0.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://vrfi1sk8a0.jobs.feishu.cn/379481/position/{id}/detail' } },
  { group: '汽车', name: '蔚来', adapter: 'byte', byte: { base: 'https://nio.jobs.feishu.cn', campusPath: '/campus/' }, url: 'https://nio.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://nio.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '科技', name: '零一万物', adapter: 'byte', byte: { base: 'https://01ai.jobs.feishu.cn', socialPath: '/index/position/', section: 'social' }, url: 'https://01ai.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://01ai.jobs.feishu.cn/index/position/{id}/detail' } },
  { group: '科技', name: '智谱', adapter: 'byte', byte: { base: 'https://zhipu-ai.jobs.feishu.cn', socialPath: '/index/position/', section: 'social' }, url: 'https://zhipu-ai.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://zhipu-ai.jobs.feishu.cn/index/position/{id}/detail' } },
  { group: '科技', name: '智元机器人', adapter: 'byte', byte: { base: 'https://agirobot.jobs.feishu.cn', campusPath: '/campusrecruitment/position/' }, url: 'https://agirobot.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://agirobot.jobs.feishu.cn/campusrecruitment/position/{id}/detail' } },
  { group: '游戏', name: '完美世界', adapter: 'moka', moka: { org: 'pwrd', siteId: '140155', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/pwrd/140155' },
  { group: '游戏', name: '鹰角网络', adapter: 'moka', moka: { org: 'hypergryph', siteId: '26326', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/hypergryph/26326' },
  // 自研系统（接口已逆向，参考 job-pro）
  { group: '物流', name: '顺丰', adapter: 'sf', url: 'https://campus.sf-express.com', reach: { type: 'direct', urlTemplate: 'https://campus.sf-express.com/#/postDetail/{id}' } },
  { group: '汽车', name: '理想汽车', adapter: 'liauto', url: 'https://www.lixiang.com/employ/campus.html', reach: { type: 'direct', urlTemplate: 'https://www.lixiang.com/job/detail/{id}.html' } },
  { group: '汽车', name: '比亚迪', adapter: 'byd', url: 'https://job.byd.com', reach: { type: 'direct', urlTemplate: 'https://job.byd.com/portal/pc/#/social/detail?positionCode={id}' } },
  { group: '保险', name: '中国平安', adapter: 'pingan', url: 'https://campus.pingan.com', reach: { type: 'direct', urlTemplate: 'https://campus.pingan.com/positionDetail?positionId={id}' } },
  { group: '半导体', name: '地平线', adapter: 'wecruit', suiteId: 'SU6409ef49bef57c635fd390a6', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU6409ef49bef57c635fd390a6/pb/detail.html?postId={id}' } },

  // ============ 金融（系统分散：zhiye / 北森微招聘 / 大易 / 自研） ============
  { group: '券商', name: '中国银河证券', adapter: 'zhiye', subdomain: 'chinastock', path: 'custom/campus' },
  { group: '券商', name: '光大证券', adapter: 'zhiye', subdomain: 'ebscn', path: 'campus/jobs' },
  { group: '券商', name: '国金证券', adapter: 'zhiye', subdomain: 'gjzq', path: 'campus/jobs' },
  { group: '银行', name: '工商银行', adapter: null, system: '自研', url: 'https://job.icbc.com.cn' },
  { group: '银行', name: '建设银行', adapter: null, system: '自研', url: 'https://job.ccb.com' },
  { group: '银行', name: '农业银行', adapter: null, system: '自研', url: 'https://career.abchina.com.cn' },
  { group: '银行', name: '中国银行', adapter: null, system: '自研', url: '' },
  { group: '银行', name: '招商银行', adapter: null, system: '自研', url: 'https://career.cmbchina.com' },
  { group: '保险', name: '中国平安', adapter: null, system: '自研', url: 'https://talent.pingan.com' },
  { group: '券商', name: '中信证券', adapter: null, system: '自研', url: '' },
  { group: '券商', name: '国泰君安', adapter: null, system: '自研', url: 'https://hr.gtja.com' },
  { group: '基金', name: '南方基金', adapter: 'hotjob', suiteId: 'SU6138665dbef57c3b63841399', url: 'https://wecruit.hotjob.cn/SU6138665dbef57c3b63841399/pb/index.html' },
  { group: '券商', name: '广发证券', adapter: 'hotjob', suiteId: 'SU625527c30dcad4021443cdda', url: 'https://wecruit.hotjob.cn/SU625527c30dcad4021443cdda/pb/index.html' },
  { group: '券商', name: '华泰证券', adapter: 'hotjob', suiteId: 'SU6419745cbef57c635fe10142', url: 'https://wecruit.hotjob.cn/SU6419745cbef57c635fe10142/pb/index.html' },
  { group: '银行', name: '中信银行', adapter: null, system: '用友大易', url: '' },
  { group: '银行', name: '兴业银行', adapter: null, system: '用友大易', url: '' },
  { group: '基金', name: '易方达基金', adapter: 'wecruit', suiteId: 'SU6a8fb99e1ad6db7cf83eb885', projectCode: '202701', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU6a8fb99e1ad6db7cf83eb885/pb/detail.html?postId={id}' } },
  { group: '基金', name: '华夏基金', adapter: 'zhiye', subdomain: 'chinaamc', url: 'https://chinaamc.zhiye.com' },
  // 广发基金无独立门户（job.gffunds.com.cn 已失效），其岗位并入广发证券集团门户 gf.hotjob.cn（同 suiteId SU625527...），见上方「广发证券」

  // ============ 已适配 zhiye 的其他公司 ============
  { group: '科技', name: '北森', adapter: 'zhiye', subdomain: 'beisen' },
  { group: '科技', name: '金证科技', adapter: 'zhiye', subdomain: 'szkingdom1' },
  { group: '科技', name: '鼎桥技术', adapter: 'zhiye', subdomain: 'td-tech' },
  { group: '科技', name: '光宝科技', adapter: 'zhiye', subdomain: 'liteon' },
  { group: '科技', name: '水晶光电', adapter: 'zhiye', subdomain: 'crystal-optech1' },
  { group: '机械装备', name: '三一集团', adapter: 'zhiye', subdomain: 'sany' },
  { group: '汽车', name: '奇瑞汽车', adapter: 'zhiye', subdomain: 'chery' },
  { group: '新能源', name: '欣旺达', adapter: 'zhiye', subdomain: 'sunwodacampus' },
  { group: '央企国企', name: '中国外运', adapter: 'zhiye', subdomain: 'sinotrans' },
  { group: '央企国企', name: '中国通用技术集团', adapter: 'zhiye', subdomain: 'genertec' },
  { group: '央企国企', name: '航天三院', adapter: 'zhiye', subdomain: 'casic' },
  { group: '央企国企', name: '中国航发黎明', adapter: 'zhiye', subdomain: 'aeccslaeg' },
  { group: '央企国企', name: '湖北联投', adapter: 'zhiye', subdomain: 'hblt' },
  { group: '央企国企', name: '广东南粤集团', adapter: 'zhiye', subdomain: 'gdadri' },
  { group: '制药', name: '药明康德', adapter: 'zhiye', subdomain: 'wuxiapptec' },
  { group: '制药', name: '泰德制药', adapter: 'zhiye', subdomain: 'tidepharm' },
  { group: '制药', name: '晶易医药', adapter: 'zhiye', subdomain: 'king-eagle' },
  { group: '制药', name: '艾迪医药', adapter: 'zhiye', subdomain: 'aidea' },
  { group: '半导体', name: '长江存储', adapter: 'zhiye', subdomain: 'ymtc' },
  { group: '半导体', name: '江波龙', adapter: 'zhiye', subdomain: 'longsys', path: 'campus/jobs' },
  { group: '半导体', name: '兆易创新', adapter: 'moka', moka: { org: 'gigadevice', siteId: '92215', base: 'https://app.mokahr.com', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/gigadevice/92215' },
  { group: '半导体', name: '佰维存储', adapter: 'zhiye', subdomain: 'biwin', path: 'campus/jobs' },
  { group: '半导体', name: '长鑫存储', adapter: 'zhiye', subdomain: 'cxmt', path: 'campus/jobs' },
  { group: '半导体', name: '中国电科36所', adapter: 'zhiye', subdomain: 'cetc36' },
  { group: '化工', name: '金发科技', adapter: 'zhiye', subdomain: 'kingfa' },
  { group: '游戏', name: '三七互娱', adapter: 'moka', moka: { org: '37', siteId: '58016', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/37/58016' },
  { group: '游戏', name: '趣加', adapter: 'moka', moka: { org: 'funplus01', siteId: '147931', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/funplus01/147931' },
  { group: '游戏', name: '巨人网络', adapter: 'moka', moka: { org: 'ztgame', siteId: '92438', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/ztgame/92438' },
  { group: '游戏', name: '库洛游戏', adapter: 'byte', byte: { base: 'https://kurogame.jobs.feishu.cn', campusPath: '/campus/position/', section: 'campus' }, url: 'https://kurogame.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://kurogame.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '游戏', name: '紫龙游戏', adapter: 'moka', moka: { org: 'zlongame', siteId: '140110', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zlongame/140110' },
  { group: '游戏', name: '沐瞳科技', adapter: 'byte', byte: { base: 'https://moonton.jobs.feishu.cn', campusPath: '/campus/position/', section: 'campus' }, url: 'https://moonton.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://moonton.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '游戏', name: '悠星网络', adapter: 'moka', moka: { org: 'yostar', siteId: '26843', base: 'https://app.mokahr.com', pathPrefix: 'apply', section: 'campus' }, url: 'https://app.mokahr.com/apply/yostar/26843' },
  { group: '游戏', name: '散爆网络', adapter: 'moka', moka: { org: 'micateam', siteId: '146166', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/micateam/146166' },
  { group: '游戏', name: '掌趣科技', adapter: 'moka', moka: { org: 'playcrab', siteId: '43628', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/playcrab/43628' },
  { group: '游戏', name: '盛趣游戏', adapter: 'moka', moka: { org: 'shengqu', siteId: '96336', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/shengqu/96336' },
  { group: '游戏', name: '点触科技', adapter: 'moka', moka: { org: 'dianchu', siteId: '144217', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/dianchu/144217' },
  { group: '半导体', name: '汇顶科技', adapter: 'zhiye', subdomain: 'goodix', path: 'campus/jobs' },
  { group: '半导体', name: '豪威集团', adapter: 'zhiye', subdomain: 'ovt-omnivision', path: 'campus/jobs' },
  { group: '半导体', name: '晶合集成', adapter: 'zhiye', subdomain: 'nexchip', path: 'campus/jobs' },
  { group: '半导体', name: '华海清科', adapter: 'zhiye', subdomain: 'hwatsing1', path: 'campus/jobs' },
  { group: '半导体', name: '卓胜微', adapter: 'zhiye', subdomain: 'maxscend', path: 'campus/jobs' },
  { group: '半导体', name: '恒玄科技', adapter: 'zhiye', subdomain: 'bestechnic', path: 'campus/jobs' },
  { group: '半导体', name: '华虹集团', adapter: 'moka', moka: { org: 'huahong', siteId: '78009', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/huahong/78009' },
  { group: '半导体', name: '中微公司', adapter: 'moka', moka: { org: 'amec', siteId: '4362', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/amec/4362' },
  { group: '半导体', name: '斯达半导', adapter: 'moka', moka: { org: 'powersemi', siteId: '101981', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/powersemi/101981' },
  { group: '半导体', name: '思瑞浦', adapter: 'moka', moka: { org: '3peakic', siteId: '67894', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/3peakic/67894' },
  { group: '半导体', name: '紫光展锐', adapter: 'wecruit', suiteId: 'SU62964975bef57c6df7b40e20', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU62964975bef57c6df7b40e20/pb/detail.html?postId={id}' } },
  { group: '汽车', name: '长安汽车', adapter: 'zhiye', subdomain: 'changan', path: 'campus/jobs' },
  { group: '汽车', name: '小鹏汽车', adapter: 'byte', byte: { base: 'https://xiaopeng.jobs.feishu.cn', campusPath: '/campus/position/', section: 'campus' }, url: 'https://xiaopeng.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://xiaopeng.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '汽车', name: '零跑汽车', adapter: 'zhiye', subdomain: 'leapmotor', path: 'campus/jobs' },
  { group: '汽车', name: '赛力斯', adapter: 'zhiye', subdomain: 'sokon', path: 'campus/jobs' },
  { group: '新能源', name: '宁德时代', adapter: 'moka', moka: { org: 'catlhr', siteId: '148948', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/catlhr/148948' },
  { group: '新能源', name: '亿纬锂能', adapter: 'wecruit', suiteId: 'SU630487ca0dcad45aa7768a79', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU630487ca0dcad45aa7768a79/pb/detail.html?postId={id}' } },
  { group: '机械装备', name: '先导智能', adapter: 'zhiye', subdomain: 'leadchina', path: 'campus/jobs' },
  { group: '消费电子', name: '歌尔股份', adapter: 'wecruit', suiteId: 'SU65dd9ebd1c240e4b11c4f491', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU65dd9ebd1c240e4b11c4f491/pb/detail.html?postId={id}' } },
  { group: '机械装备', name: '三一重工', adapter: 'zhiye', subdomain: 'sanycampus', path: 'campus/jobs' },
  { group: '机械装备', name: '徐工集团', adapter: 'moka', moka: { org: 'xcmg', siteId: '148091', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/xcmg/148091' },
  { group: '机械装备', name: '中联重科', adapter: 'wecruit', suiteId: 'SU60a6449a2f9d2430fdc11a19', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU60a6449a2f9d2430fdc11a19/pb/detail.html?postId={id}' } },
  { group: '机械装备', name: '柳工', adapter: 'wecruit', suiteId: 'SU6132e87abef57c3b637dcb71', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU6132e87abef57c3b637dcb71/pb/detail.html?postId={id}' } },
  { group: '基金', name: '嘉实基金', adapter: 'moka', moka: { org: 'jsfund', siteId: '43906', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/jsfund/43906' },
  { group: '保险', name: '中国人保', adapter: 'zhiye', subdomain: 'picc', path: 'campus/jobs' },
  { group: '保险', name: '泰康保险', adapter: 'zhiye', subdomain: 'jobtaikang', path: 'campus/jobs' },
  { group: '保险', name: '新华保险', adapter: 'zhiye', subdomain: 'nci', path: 'campus/jobs' },
  { group: '游戏', name: '乐元素', adapter: 'moka', moka: { org: 'leyuansu', siteId: '164275', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/leyuansu/164275' },
  { group: '游戏', name: '祖龙娱乐', adapter: 'moka', moka: { org: 'zulong', siteId: '25158', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zulong/25158' },
  { group: '半导体', name: '全志科技', adapter: 'moka', moka: { org: 'allwinnertech', siteId: '43436', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/allwinnertech/43436' },
  { group: '半导体', name: '瑞芯微', adapter: 'moka', moka: { org: 'rock-chips', siteId: '44102', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/rock-chips/44102' },
  { group: '半导体', name: '三安光电', adapter: 'zhiye', subdomain: 'sanan-e', path: 'campus/jobs' },
  { group: '汽车', name: '长城汽车', adapter: 'wecruit', suiteId: 'SU692d3058ea11b01b6c54d0ea', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU692d3058ea11b01b6c54d0ea/pb/detail.html?postId={id}' } },
  { group: '消费电子', name: 'TCL', adapter: 'wecruit', suiteId: 'SU64893571bef57c16d356b99e', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU64893571bef57c16d356b99e/pb/detail.html?postId={id}' } },
  { group: '央企国企', name: '中核集团', adapter: 'zhiye', subdomain: 'cnnc', path: 'campus/jobs' },
  { group: '央企国企', name: '中国铁建', adapter: 'zhiye', subdomain: 'crcci', path: 'campus/jobs' },
  { group: '央企国企', name: '中国交建', adapter: 'zhiye', subdomain: 'ccccltd', path: 'campus/jobs' },
  { group: '央企国企', name: '招商局集团', adapter: 'zhiye', subdomain: 'cmhk', path: 'campus/jobs' },
  { group: '央企国企', name: '中国兵器工业集团', adapter: 'zhiye', subdomain: 'norincogroupzhaopin', path: 'campus/jobs' },
  { group: '央企国企', name: '中国船舶集团', adapter: 'zhiye', subdomain: 'cssc', path: 'campus/jobs' },
  { group: '央企国企', name: '中国中化', adapter: 'wecruit', suiteId: 'SU610b91ee0dcad4106ff11c21', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU610b91ee0dcad4106ff11c21/pb/detail.html?postId={id}' } },
  { group: '制药', name: '恒瑞医药', adapter: 'moka', moka: { org: 'hengrui', siteId: '145997', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/hengrui/145997' },
  { group: '制药', name: '上海医药', adapter: 'moka', moka: { org: 'sphchina', siteId: '37653', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/sphchina/37653' },
  { group: '生物医药', name: '智飞生物', adapter: 'moka', moka: { org: 'zfsw', siteId: '46252', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zfsw/46252' },
  { group: '制药', name: '康龙化成', adapter: 'moka', moka: { org: 'pharmaron', siteId: '74162', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/pharmaron/74162' },
  { group: '医疗器械', name: '微创医疗', adapter: 'moka', moka: { org: 'microport', siteId: '56155', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/microport/56155' },
  { group: '医疗器械', name: '联影医疗', adapter: 'zhiye', subdomain: 'united-imaging', path: 'campus/jobs' },
  { group: '生物医药', name: '信达生物', adapter: 'zhiye', subdomain: 'innoventbio', path: 'campus/jobs' },
  { group: '制药', name: '复星医药', adapter: 'zhiye', subdomain: 'fosunpharma', path: 'campus/jobs' },
  { group: '制药', name: '正大天晴', adapter: 'zhiye', subdomain: 'cttq', path: 'campus/jobs' },
  { group: '制药', name: '齐鲁制药', adapter: 'zhiye', subdomain: 'qilu-pharma', path: 'campus/jobs' },
  { group: '生物医药', name: '君实生物', adapter: 'zhiye', subdomain: 'junshibiosciences', path: 'campus/jobs' },
  { group: '制药', name: '三生制药', adapter: 'zhiye', subdomain: '3sbio', path: 'campus/jobs' },
  { group: '制药', name: '泰格医药', adapter: 'zhiye', subdomain: 'tigermed', path: 'campus/jobs' },
  { group: '制药', name: '翰森制药', adapter: 'zhiye', subdomain: 'hspharm', path: 'campus/jobs' },
  { group: '医疗器械', name: '威高集团', adapter: 'zhiye', subdomain: 'weigao', path: 'campus/jobs' },
  { group: '医疗器械', name: '鱼跃医疗', adapter: 'zhiye', subdomain: 'yuwellhr', path: 'campus/jobs' },
  { group: '生物医药', name: '华大基因', adapter: 'zhiye', subdomain: 'genomics', path: 'campus/jobs' },
  { group: '制药', name: '凯莱英', adapter: 'zhiye', subdomain: 'asymchem', path: 'campus/jobs' },
  { group: '制药', name: '华润三九', adapter: 'wecruit', suiteId: 'SU613834ecbef57c3b6383b50e', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU613834ecbef57c3b6383b50e/pb/detail.html?postId={id}' } },
  { group: '新能源', name: '金风科技', adapter: 'zhiye', subdomain: 'goldwind', path: 'campus/jobs' },
{ group: '食品饮料', name: '蒙牛', adapter: 'zhiye', subdomain: 'mengniu', path: 'campus/jobs' },
  { group: '食品饮料', name: '双汇', adapter: 'zhiye', subdomain: 'shuanghui', path: 'campus/jobs' },
  { group: '食品饮料', name: '白象食品', adapter: 'zhiye', subdomain: 'baixiangfood', path: 'campus/jobs' },
  { group: '食品饮料', name: '洽洽食品', adapter: 'zhiye', subdomain: 'qiaqiafood', path: 'campus/jobs' },
  { group: '零售消费', name: '华润万家', adapter: 'wecruit', suiteId: 'SU615189f40dcad47003dc4af7', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU615189f40dcad47003dc4af7/pb/detail.html?postId={id}' } },
  { group: '零售消费', name: '瑞幸咖啡', adapter: 'moka', moka: { org: 'lkcoffee', siteId: '45257', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/lkcoffee/45257' },
  { group: '零售消费', name: '古茗', adapter: 'moka', moka: { org: 'guming', siteId: '39377', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/guming/39377' },
  { group: '汽车', name: '岚图汽车', adapter: 'moka', moka: { org: 'voyah', siteId: '146293', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/voyah/146293' },
  { group: '汽车', name: '特斯拉', adapter: 'moka', moka: { org: 'tesla', siteId: '41460', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/tesla/41460' },
  { group: '汽车', name: '吉利控股', adapter: 'moka', moka: { org: 'geely', siteId: '102225', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/geely/102225' },
  { group: '汽车', name: '上汽乘用车', adapter: 'zhiye', subdomain: 'smpv', path: 'campus/jobs' },
  { group: '汽车', name: '北汽集团', adapter: 'zhiye', subdomain: 'baicgroup', path: 'campus/jobs' },
  { group: '汽车', name: '江铃汽车', adapter: 'zhiye', subdomain: 'jmc', path: 'campus/jobs' },
  { group: '汽车', name: '福田汽车', adapter: 'zhiye', subdomain: 'futurefoton', path: 'campus/jobs' },
  { group: '新能源', name: '中创新航', adapter: 'zhiye', subdomain: 'calbjs', path: 'campus/jobs' },
  { group: '新能源', name: '蜂巢能源', adapter: 'zhiye', subdomain: 'svolt', path: 'campus/jobs' },
  { group: '新能源', name: '孚能科技', adapter: 'zhiye', subdomain: 'farasisenergy', path: 'campus/jobs' },
  { group: '汽车', name: '博世中国', adapter: 'moka', moka: { org: 'bosch', siteId: '73873', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/bosch/73873' },
  { group: '汽车', name: '德赛西威', adapter: 'byte', byte: { base: 'https://yesv-desaysv.jobs.feishu.cn', campusPath: '/campus/position/', section: 'campus' }, url: 'https://yesv-desaysv.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://yesv-desaysv.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '汽车', name: '均胜电子', adapter: 'moka', moka: { org: 'joyson', siteId: '94311', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/joyson/94311' },
  { group: '医疗器械', name: '迈瑞医疗', adapter: 'zhiye', subdomain: 'mindray', path: 'campus/jobs' },
  { group: '制药', name: '科伦药业', adapter: 'zhiye', subdomain: 'kelun', path: 'campus/jobs' },
  { group: '制药', name: '先声药业', adapter: 'wecruit', suiteId: 'SU61458d83bef57c54dcb4e43f', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU61458d83bef57c54dcb4e43f/pb/detail.html?postId={id}' } },
  { group: '生物医药', name: '康希诺', adapter: 'zhiye', subdomain: 'cansinotech', path: 'campus/jobs' },
  { group: '医疗器械', name: '华大智造', adapter: 'zhiye', subdomain: 'genomics', path: 'campus/jobs' },
  { group: '医疗器械', name: '金域医学', adapter: 'zhiye', subdomain: 'kingmed', path: 'campus/jobs' },
  { group: '券商', name: '国信证券', adapter: 'zhiye', subdomain: 'guosen', path: 'campus/jobs' },
  { group: '保险', name: '中国人寿', adapter: 'zhiye', subdomain: 'chinalife', path: 'campus/jobs' },
  { group: '券商', name: '国泰海通证券', adapter: 'moka', moka: { org: 'gthtsf', siteId: '149429', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/gthtsf/149429' },
  { group: '券商', name: '东方证券', adapter: 'moka', moka: { org: 'dfzq', siteId: '5546', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/dfzq/5546' },
  { group: '券商', name: '申万宏源证券', adapter: 'moka', moka: { org: 'swhysc-job', siteId: '166086', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/swhysc-job/166086' },
  { group: '基金', name: '天弘基金', adapter: 'moka', moka: { org: 'thfund', siteId: '46219', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/thfund/46219' },
  { group: '保险', name: '众安保险', adapter: 'moka', moka: { org: 'zhongan', siteId: '71908', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zhongan/71908' },
  { group: '保险', name: '中国太保(太平洋产险)', adapter: 'moka', moka: { org: 'cpicproperty', siteId: '150956', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/cpicproperty/150956' },
  { group: '券商', name: '招商证券', adapter: 'wecruit', suiteId: 'SU629dbc0c0dcad452299bc0f7', url: 'https://wecruit.hotjob.cn', reach: { type: 'direct', urlTemplate: 'https://wecruit.hotjob.cn/SU629dbc0c0dcad452299bc0f7/pb/detail.html?postId={id}' } },
  // ==== 重新识别落地（旧版 zhiye 社招/实习有岗位，校招 2027 届 9 月开）====
  { group: '食品饮料', name: '良品铺子', adapter: 'zhiye', subdomain: 'lppz', path: 'campus/jobs' },
  { group: '食品饮料', name: '东鹏饮料', adapter: 'zhiye', subdomain: 'dongpeng', path: 'campus/jobs' },
  { group: '零售消费', name: '永辉超市', adapter: 'zhiye', subdomain: 'yhchaoshi', path: 'campus/jobs' },
  { group: '零售消费', name: '星巴克', adapter: 'zhiye', subdomain: 'starbucks', path: 'campus/jobs' },
  { group: '汽车', name: '江淮汽车', adapter: 'zhiye', subdomain: 'jac', path: 'campus/jobs' },
  { group: '新能源', name: '国轩高科', adapter: 'zhiye', subdomain: 'gotion', path: 'campus/jobs' },
  { group: '汽车', name: '潍柴动力', adapter: 'zhiye', subdomain: 'weichai', path: 'campus/jobs' },
  { group: '制药', name: '扬子江药业', adapter: 'zhiye', subdomain: 'yangzijiang', path: 'campus/jobs' },
  { group: '医疗器械', name: '东软医疗', adapter: 'zhiye', subdomain: 'neusoftmedical', path: 'campus/jobs' },
  { group: '制药', name: '贝达药业', adapter: 'zhiye', subdomain: 'bettapharma', path: 'campus/jobs' },
  { group: '券商', name: '中金公司', adapter: 'zhiye', subdomain: 'cicc', path: 'campus/jobs' },
  { group: '基金', name: '招商基金', adapter: 'zhiye', subdomain: 'cmfchina', path: 'campus/jobs' },
  { group: '保险', name: '中国太平', adapter: 'zhiye', subdomain: 'cntp', path: 'campus/jobs' },
  { group: '银行', name: '北京银行', adapter: 'zhiye', subdomain: 'bankofbeijing', path: 'campus/jobs' },
  // ==== subdomain 纠错 + ATS 复核（森马/东方财富实为 moka，上海家化路径 /alljob）====
  { group: '食品饮料', name: '李锦记', adapter: 'zhiye', subdomain: 'lkksh', path: 'campus/jobs' },
  { group: '零售消费', name: '森马', adapter: 'moka', moka: { org: 'senma', siteId: '142913', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/senma/142913' },
  { group: '零售消费', name: '上海家化', adapter: 'zhiye', subdomain: 'shjahwa', path: 'alljob' },
  { group: '金融科技', name: '东方财富', adapter: 'moka', moka: { org: 'eastmoney', siteId: '57971', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/eastmoney/57971' },
  { group: '零售消费', name: '屈臣氏', adapter: 'moka', moka: { org: 'watsons', siteId: '150132', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/watsons/150132' },
  { group: '制药', name: '百济神州', adapter: 'moka', moka: { org: 'beigene', siteId: '98934', base: 'https://app.mokahr.com', pathPrefix: 'social-recruitment', section: 'social' }, url: 'https://app.mokahr.com/social-recruitment/beigene/98934' },
  // ==== workflow 调研落地（地产/物流/教育/游戏）====
  { group: '地产建筑', name: '中海地产', adapter: 'zhiye', subdomain: 'coli688', path: 'campus/jobs' },
  { group: '地产建筑', name: '保利发展', adapter: 'zhiye', subdomain: 'polycareer', path: 'campus/jobs' },
  { group: '地产建筑', name: '中国建筑', adapter: 'zhiye', subdomain: 'cscec', path: 'campus/jobs' },
  { group: '地产建筑', name: '招商蛇口', adapter: 'zhiye', subdomain: 'cmsk1979', path: 'campus/jobs' },
  { group: '物流', name: '德邦物流', adapter: 'zhiye', subdomain: 'deppon', path: 'campus/jobs' },
  { group: '物流', name: '申通快递', adapter: 'moka', moka: { org: 'sto', siteId: '126265', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/sto/126265' },
  { group: '物流', name: '货拉拉', adapter: 'moka', moka: { org: 'huolalahr', siteId: '98660', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/huolalahr/98660' },
  { group: '教育', name: '好未来', adapter: 'moka', moka: { org: 'tal', siteId: '169887', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/tal/169887' },
  { group: '教育', name: '作业帮', adapter: 'moka', moka: { org: 'zuoyebang', siteId: '144908', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zuoyebang/144908' },
  { group: '教育', name: '粉笔', adapter: 'moka', moka: { org: 'fenbi', siteId: '47742', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/fenbi/47742' },
  { group: '游戏', name: '莉莉丝', adapter: 'byte', byte: { base: 'https://lilithgames.jobs.feishu.cn', campusPath: '/campus/', section: 'campus' }, url: 'https://lilithgames.jobs.feishu.cn', reach: { type: 'direct', urlTemplate: 'https://lilithgames.jobs.feishu.cn/campus/position/{id}/detail' } },
  { group: '食品饮料', name: '泸州老窖', adapter: 'zhiye', subdomain: 'lzlj3', path: 'campus/jobs' },
  { group: '新能源', name: '晶科能源', adapter: 'moka', moka: { org: 'jinkosolar', siteId: '41896', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/jinkosolar/41896' },
  { group: '新能源', name: '阳光电源', adapter: 'moka', moka: { org: 'sungrow', siteId: '94416', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/sungrow/94416' },
  { group: '软件', name: '东软集团', adapter: 'zhiye', subdomain: 'neusoft-campus', path: 'campus/jobs' },
  { group: '软件', name: '奇安信', adapter: 'moka', moka: { org: 'qianxin', siteId: '29182', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/qianxin/29182' },
  { group: '机械装备', name: '汇川技术', adapter: 'zhiye', subdomain: 'inovance', path: 'campus/jobs' },
  { group: '机械装备', name: '大族激光', adapter: 'moka', moka: { org: 'hanslaser', siteId: '46383', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/hanslaser/46383' },
  { group: '半导体', name: '中芯国际', adapter: 'zhiye', subdomain: 'smics', path: 'campus/jobs' },
  { group: '半导体', name: '海光信息', adapter: 'moka', moka: { org: 'hygon', siteId: '169939', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/hygon/169939' },
  { group: '机械装备', name: '铁建重工', adapter: 'zhiye', subdomain: 'crchi', path: 'campus/jobs' },
  { group: '农业', name: '牧原股份', adapter: 'moka', moka: { org: 'muyuan', siteId: '70116', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/muyuan/70116' },
  { group: '农业', name: '温氏股份', adapter: 'moka', moka: { org: 'wens', siteId: '92366', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/wens/92366' },
  { group: '农业', name: '通威股份', adapter: 'zhiye', subdomain: 'tongwei', path: 'campus/jobs' },
  { group: '化工', name: '巨化集团', adapter: 'zhiye', subdomain: 'juhua', path: 'campus/jobs' },
  { group: '化工', name: '华峰集团', adapter: 'zhiye', subdomain: 'huafeng', path: 'campus/jobs' },
  { group: '化工', name: '合盛硅业', adapter: 'zhiye', subdomain: 'hoshine', path: 'campus/jobs' },
  { group: '化工', name: '东方盛虹', adapter: 'zhiye', subdomain: 'shenghonggroup', path: 'campus/jobs' },
  { group: '化工', name: '圣泉集团', adapter: 'zhiye', subdomain: 'shengquan', path: 'campus/jobs' },
  { group: '化工', name: '新和成', adapter: 'zhiye', subdomain: 'xinhecheng1', path: 'campus/jobs' },
  { group: '消费电子', name: '传音控股', adapter: 'zhiye', subdomain: 'transsion', path: 'campus/jobs' },
  { group: '消费电子', name: '瑞声科技', adapter: 'zhiye', subdomain: 'aac', path: 'campus/jobs' },
  { group: '消费电子', name: '京东方', adapter: 'zhiye', subdomain: 'boe', path: 'campus/jobs' },
  { group: '消费电子', name: '格兰仕', adapter: 'zhiye', subdomain: 'galanz', path: 'campus/jobs' },
  { group: '消费电子', name: '深南电路', adapter: 'zhiye', subdomain: 'scc', path: 'campus/jobs' },
  { group: '半导体', name: '韦尔股份', adapter: 'zhiye', subdomain: 'ovt-omnivision', path: 'campus/jobs' },
  { group: '消费电子', name: '三星', adapter: 'zhiye', subdomain: 'dearsamsung', path: 'campus/jobs' },
  { group: '新能源', name: '紫金矿业', adapter: 'moka', moka: { org: 'zijinmining', siteId: '117957', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zijinmining/117957' },
  { group: '医疗器械', name: 'GE医疗', adapter: 'moka', moka: { org: 'gehc', siteId: '142250', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/gehc/142250' },
  { group: '消费电子', name: '松下', adapter: 'moka', moka: { org: 'panasonic', siteId: '41989', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/panasonic/41989' },
  { group: '药企', name: '辉瑞', adapter: 'tupu360', tupu360: { base: 'https://careersite.tupu360.com', tenant: 'pfizercampus' }, url: 'https://careersite.tupu360.com/pfizercampus/position/index' },
  { group: '汽车', name: '宝马', adapter: 'tupu360', tupu360: { base: 'https://careersite.tupu360.com', tenant: 'bmw-brilliance' }, url: 'https://careersite.tupu360.com/bmw-brilliance/position/index' },
  { group: '基金', name: '博时基金', adapter: 'hotjob', suiteId: 'SU65f940241c240e0a2275bda8', base: 'https://bosera.hotjob.cn', url: 'https://bosera.hotjob.cn' },
  { group: '机械装备', name: '中国中车', adapter: 'hotjob', suiteId: 'SU64d47c466202cc36e27a52d4', base: 'https://crrc.hotjob.cn', url: 'https://crrc.hotjob.cn' },
  { group: '汽车', name: '东风汽车', adapter: 'moka', moka: { org: 'dfmc', siteId: '168424', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/dfmc/168424' },
  { group: '半导体', name: '紫光国微', adapter: 'zhiye', subdomain: 'szssmec1', path: 'campus/jobs' },
  { group: '机械装备', name: '潍柴动力', adapter: 'zhiye', subdomain: 'weichai', path: 'campus/jobs' },
  { group: '新能源', name: '隆基绿能', adapter: 'hotjob', suiteId: 'SU649d2f9c0dcad4644b43df7e', base: 'https://longi.hotjob.cn', url: 'https://longi.hotjob.cn' },
  { group: '半导体', name: '北方华创', adapter: 'zhiye', base: 'https://career.naura.com', url: 'https://career.naura.com/campus' },
  { group: '半导体', name: '闻泰科技', adapter: 'zhiye', base: 'http://jobs.wingtech.com', url: 'http://jobs.wingtech.com/campus' },
  { group: '汽车', name: '博世', adapter: 'moka', moka: { org: 'bosch', siteId: '73873', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/bosch/73873' },
  { group: '软件', name: '恒生电子', adapter: 'zhiye', base: 'https://campus.hundsun.com', url: 'https://campus.hundsun.com' },
  { group: '半导体', name: '国科微', adapter: 'zhiye', subdomain: 'goke', path: 'campus/jobs' },
  { group: '新能源', name: '天合光能', adapter: 'moka', moka: { org: 'trinasolar', siteId: '58070', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/trinasolar/58070' },
  { group: '央企国企', name: '中国五矿', adapter: 'hotjob', suiteId: 'SU62f37858bef57c29ead8adab', base: 'https://wecruit.hotjob.cn', url: 'https://zhaopin.minmetals.com.cn' },
  { group: '食品饮料', name: '海天味业', adapter: 'hotjob', suiteId: 'SU6322dfb70dcad46a862da4c5', base: 'https://haday.hotjob.cn', url: 'https://haday.hotjob.cn' },
  { group: '化工', name: '万华化学', adapter: 'hotjob', suiteId: 'SU6a7ad69c43154813049755d7', base: 'https://whchem.hotjob.cn', url: 'https://whchem.hotjob.cn' },
  { group: '消费电子', name: '歌尔股份', adapter: 'hotjob', suiteId: 'SU65dd9ebd1c240e4b11c4f491', base: 'https://goertek.hotjob.cn', url: 'https://goertek.hotjob.cn' },
  { group: '地产建筑', name: '中国金茂', adapter: 'hotjob', suiteId: 'SU64f689866202cc040145b4b5', base: 'https://jinmao.hotjob.cn', url: 'https://jinmao.hotjob.cn' },
  { group: '半导体', name: '英特尔', adapter: 'workday', workday: { tenant: 'intel' }, url: 'https://intel.wd1.myworkdayjobs.com' },
  { group: '药企', name: '丽珠集团', adapter: 'byte', byte: { base: 'https://j0eukrlohu.jobs.feishu.cn', campusPath: '/968157/position/', section: 'campus' }, url: 'https://j0eukrlohu.jobs.feishu.cn' },
  { group: '消费电子', name: '龙旗科技', adapter: 'zhiye', subdomain: 'longcheerzp1', path: 'campus/jobs' },
  { group: '消费电子', name: '大疆创新', adapter: 'moka', moka: { org: 'dji', siteId: '143359', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/dji/143359' },
  { group: '消费电子', name: '中兴通讯', adapter: 'moka', moka: { org: 'zte', siteId: '46903', base: 'https://app.mokahr.com', pathPrefix: 'campus-recruitment', section: 'campus' }, url: 'https://app.mokahr.com/campus-recruitment/zte/46903' },
  { group: '基金', name: '富国基金', adapter: 'moka', moka: { org: 'fullgoal', siteId: '72198', base: 'https://app.mokahr.com', pathPrefix: 'campus_apply', section: 'campus' }, url: 'https://app.mokahr.com/campus_apply/fullgoal/72198' },
  { group: '消费电子', name: '立讯精密', adapter: 'hotjob', suiteId: 'SU601778b25d83dc07207323', base: 'https://luxshare.hotjob.cn', url: 'https://luxshare.hotjob.cn' },
  { group: '央企国企', name: '国聘网·校招', adapter: 'iguopin', iguopin: { nature: '115xW5oQ', allCities: true }, url: 'https://www.iguopin.com' },
  { group: '央企国企', name: '国聘网·社招', adapter: 'iguopin', iguopin: { nature: '113Fc6wc', allCities: true }, url: 'https://www.iguopin.com' },
  { group: '央企国企', name: '国聘网·实习', adapter: 'iguopin', iguopin: { nature: '11bTac9', allCities: true }, url: 'https://www.iguopin.com' },
];

// 按 group 分组返回（供前端下拉）
function getCompanies() {
  const groups = {};
  for (const c of COMPANIES) (groups[c.group] ||= []).push(c);
  return Object.entries(groups).map(([group, companies]) => ({ group, companies }));
}

function findCompany(name) {
  return COMPANIES.find((c) => c.name === name);
}

module.exports = { COMPANIES, getCompanies, findCompany };
